/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package ocpmcp

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/json"
	"encoding/pem"
	"errors"
	"io"
	"log"
	"math/big"
	"net"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

const mcpProcessTrustChildEnv = "OLS_MCP_PROCESS_TRUST_CHILD"

type mcpProcessTrustProbe struct {
	Name     string
	URL      string
	RootFile string
	Failure  string
}

// TestMCPProcessTrustLoading exercises Go's process-wide trust loading, not a
// manually assembled CertPool. Re-exec avoids any SystemCertPool cached by other
// tests. SSL_CERT_FILE below simulates an image's already configured root file;
// it is NOT an environment override supplied by the operator's runtime contract.
func TestMCPProcessTrustLoading(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("SSL_CERT_DIR contract targets Go's Linux trust loader")
	}
	t.Log("Uses the operator Go toolchain, not the actual pinned FIPS MCP image; explicit temporary paths simulate existing image root files.")
	if childConfig := os.Getenv(mcpProcessTrustChildEnv); childConfig != "" {
		runMCPProcessTrustChild(t, childConfig)
		return
	}

	dir := t.TempDir()
	supplementalDir := filepath.Join(dir, "supplemental")
	if err := os.Mkdir(supplementalDir, 0700); err != nil {
		t.Fatal(err)
	}
	// Keep the system-directory prefix exactly as generated by the deployment,
	// replacing only the supplemental mount with a real temporary directory.
	prefix, ok := strings.CutSuffix(sharedCertDirectories, ":"+sharedTrustDir)
	if !ok || prefix == "" {
		t.Fatalf("unexpected shared certificate directories: %q", sharedCertDirectories)
	}
	certDirectories := prefix + ":" + supplementalDir

	var probes []mcpProcessTrustProbe
	for _, fixture := range []struct {
		name string
		file string
	}{
		{name: "image", file: filepath.Join(dir, "image-rootfile")},
		{name: "service", file: filepath.Join(supplementalDir, "service-ca.crt")},
		{name: "custom", file: filepath.Join(supplementalDir, "user-ca.crt")},
		{name: "unknown"},
	} {
		caPEM, caKeyPEM, err := generateMCPTestCA()
		if err != nil {
			t.Fatalf("generate %s CA: %v", fixture.name, err)
		}
		// Only service/custom public CA PEM goes in the supplemental directory;
		// private keys never enter it, and the image root lives in a separate file.
		if fixture.file != "" {
			if err := os.WriteFile(fixture.file, caPEM, 0600); err != nil {
				t.Fatal(err)
			}
		}
		server := newMCPProcessTrustServer(t, caPEM, caKeyPEM)
		endpoint, err := url.Parse(server.URL)
		if err != nil {
			t.Fatal(err)
		}
		endpoint.Host = net.JoinHostPort("localhost", endpoint.Port())
		probe := mcpProcessTrustProbe{Name: fixture.name, URL: endpoint.String(), RootFile: fixture.file}
		if fixture.name == "unknown" {
			probe.Failure = "unknown-authority"
		}
		probes = append(probes, probe)
		if fixture.name == "service" {
			// Leaf certificates contain DNS:localhost only, no IP SAN. The same
			// trusted server must fail verification when addressed as 127.0.0.1.
			endpoint.Host = net.JoinHostPort("127.0.0.1", endpoint.Port())
			probes = append(probes, mcpProcessTrustProbe{
				Name: "hostname-mismatch", URL: endpoint.String(), Failure: "hostname",
			})
		}
	}
	config, err := json.Marshal(probes)
	if err != nil {
		t.Fatal(err)
	}
	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	childCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(childCtx, executable, "-test.run=^TestMCPProcessTrustLoading$", "-test.v")
	// Remove inherited values rather than appending duplicate environment keys.
	for _, entry := range os.Environ() {
		key, _, _ := strings.Cut(entry, "=")
		if key != "SSL_CERT_FILE" && key != "SSL_CERT_DIR" && key != mcpProcessTrustChildEnv {
			cmd.Env = append(cmd.Env, entry)
		}
	}
	cmd.Env = append(cmd.Env,
		"SSL_CERT_FILE="+filepath.Join(dir, "image-rootfile"),
		"SSL_CERT_DIR="+certDirectories,
		mcpProcessTrustChildEnv+"="+string(config),
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("fresh-process trust probe failed (context: %v): %v\n%s", childCtx.Err(), err, output)
	}
	t.Logf("fresh-process trust probe:\n%s", output)
}

func runMCPProcessTrustChild(t *testing.T, config string) {
	t.Helper()
	var probes []mcpProcessTrustProbe
	if err := json.Unmarshal([]byte(config), &probes); err != nil {
		t.Fatal(err)
	}
	roots, err := x509.SystemCertPool()
	if err != nil {
		t.Fatalf("load system roots: %v", err)
	}
	// The fixture helper gives every CA the same subject. Verify each exact
	// certificate instead of just matching subjects, which could mask a missing
	// image root. No roots are appended here or supplied to the HTTP client.
	for _, probe := range probes {
		if probe.RootFile == "" {
			continue
		}
		data, err := os.ReadFile(probe.RootFile)
		if err != nil {
			t.Fatal(err)
		}
		cert := parseMCPProcessTrustCertificate(t, data)
		if _, err := cert.Verify(x509.VerifyOptions{Roots: roots, KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageAny}}); err != nil {
			t.Fatalf("system pool did not preserve %s root: %v", probe.Name, err)
		}
	}

	// Retain ordinary default TLS verification (nil RootCAs and no custom TLS
	// config). Disable environment proxies so these are genuinely local requests.
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.Proxy = nil
	t.Cleanup(transport.CloseIdleConnections)
	client := &http.Client{Transport: transport, Timeout: 5 * time.Second}
	for _, probe := range probes {
		t.Run(probe.Name, func(t *testing.T) {
			response, err := client.Get(probe.URL)
			if response != nil {
				defer response.Body.Close()
			}
			if probe.Failure == "" {
				if err != nil {
					t.Fatalf("trusted HTTPS request failed: %v", err)
				}
				body, err := io.ReadAll(response.Body)
				if err != nil || response.StatusCode != http.StatusOK || string(body) != "trusted backend" {
					t.Fatalf("unexpected backend response: status=%d body=%q err=%v", response.StatusCode, body, err)
				}
				return
			}
			var verificationErr *tls.CertificateVerificationError
			if !errors.As(err, &verificationErr) {
				t.Fatalf("expected TLS certificate verification failure, got %v", err)
			}
			switch probe.Failure {
			case "unknown-authority":
				var unknown x509.UnknownAuthorityError
				if !errors.As(verificationErr, &unknown) {
					t.Fatalf("expected unknown CA failure, got %v", err)
				}
			case "hostname":
				var hostname x509.HostnameError
				if !errors.As(verificationErr, &hostname) {
					t.Fatalf("expected SAN hostname failure, got %v", err)
				}
			default:
				t.Fatalf("unknown failure expectation %q", probe.Failure)
			}
		})
	}
}

func parseMCPProcessTrustCertificate(t *testing.T, data []byte) *x509.Certificate {
	t.Helper()
	block, rest := pem.Decode(data)
	if block == nil || block.Type != "CERTIFICATE" || len(strings.TrimSpace(string(rest))) != 0 {
		t.Fatal("expected exactly one certificate PEM block")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		t.Fatal(err)
	}
	return cert
}

func newMCPProcessTrustServer(t *testing.T, caPEM, caKeyPEM []byte) *httptest.Server {
	t.Helper()
	ca := parseMCPProcessTrustCertificate(t, caPEM)
	keyBlock, _ := pem.Decode(caKeyPEM)
	if keyBlock == nil || keyBlock.Type != "EC PRIVATE KEY" {
		t.Fatal("expected fixture EC private key PEM")
	}
	caKey, err := x509.ParseECPrivateKey(keyBlock.Bytes)
	if err != nil {
		t.Fatal(err)
	}
	leafKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		t.Fatal(err)
	}
	leaf := &x509.Certificate{
		SerialNumber: serial, Subject: pkix.Name{CommonName: "localhost"},
		DNSNames:  []string{"localhost"},
		NotBefore: time.Now().Add(-time.Minute), NotAfter: time.Now().Add(time.Hour),
		KeyUsage: x509.KeyUsageDigitalSignature, ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, leaf, ca, &leafKey.PublicKey, caKey)
	if err != nil {
		t.Fatal(err)
	}
	server := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_, _ = io.WriteString(w, "trusted backend")
	}))
	server.Config.ErrorLog = log.New(io.Discard, "", 0) // Expected rejected TLS handshakes.
	server.TLS = &tls.Config{
		MinVersion:   tls.VersionTLS12,
		Certificates: []tls.Certificate{{Certificate: [][]byte{der}, PrivateKey: leafKey}},
	}
	t.Cleanup(server.Close)
	server.StartTLS()
	return server
}
