//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	configv1 "github.com/openshift/api/config/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticOLSSpec) DeepCopyInto(out *AgenticOLSSpec) {
	*out = *in
	in.AgenticSandboxConfig.DeepCopyInto(&out.AgenticSandboxConfig)
	if in.TerminalTTL != nil {
		in, out := &in.TerminalTTL, &out.TerminalTTL
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticOLSSpec.
func (in *AgenticOLSSpec) DeepCopy() *AgenticOLSSpec {
	if in == nil {
		return nil
	}
	out := new(AgenticOLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsAdapterSpec) DeepCopyInto(out *AlertsAdapterSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsAdapterSpec.
func (in *AlertsAdapterSpec) DeepCopy() *AlertsAdapterSpec {
	if in == nil {
		return nil
	}
	out := new(AlertsAdapterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditConfig) DeepCopyInto(out *AuditConfig) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditConfig.
func (in *AuditConfig) DeepCopy() *AuditConfig {
	if in == nil {
		return nil
	}
	out := new(AuditConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerConfig) DeepCopyInto(out *ContainerConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerConfig.
func (in *ContainerConfig) DeepCopy() *ContainerConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationCacheSpec) DeepCopyInto(out *ConversationCacheSpec) {
	*out = *in
	out.Postgres = in.Postgres
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationCacheSpec.
func (in *ConversationCacheSpec) DeepCopy() *ConversationCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ConversationCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
	in.APIContainer.DeepCopyInto(&out.APIContainer)
	in.DataCollectorContainer.DeepCopyInto(&out.DataCollectorContainer)
	in.MCPServerContainer.DeepCopyInto(&out.MCPServerContainer)
	in.RHOKPContainer.DeepCopyInto(&out.RHOKPContainer)
	in.ConsoleContainer.DeepCopyInto(&out.ConsoleContainer)
	in.AgenticConsoleContainer.DeepCopyInto(&out.AgenticConsoleContainer)
	in.DatabaseContainer.DeepCopyInto(&out.DatabaseContainer)
	in.AlertsAdapter.DeepCopyInto(&out.AlertsAdapter)
	in.OtelCollector.DeepCopyInto(&out.OtelCollector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailsConfig) DeepCopyInto(out *GuardrailsConfig) {
	*out = *in
	if in.ToolResultInspection != nil {
		in, out := &in.ToolResultInspection, &out.ToolResultInspection
		*out = new(ToolResultInspectionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailsConfig.
func (in *GuardrailsConfig) DeepCopy() *GuardrailsConfig {
	if in == nil {
		return nil
	}
	out := new(GuardrailsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMSpec) DeepCopyInto(out *LLMSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMSpec.
func (in *LLMSpec) DeepCopy() *LLMSpec {
	if in == nil {
		return nil
	}
	out := new(LLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimiterConfig) DeepCopyInto(out *LimiterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimiterConfig.
func (in *LimiterConfig) DeepCopy() *LimiterConfig {
	if in == nil {
		return nil
	}
	out := new(LimiterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPCAKeyReference) DeepCopyInto(out *MCPCAKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPCAKeyReference.
func (in *MCPCAKeyReference) DeepCopy() *MCPCAKeyReference {
	if in == nil {
		return nil
	}
	out := new(MCPCAKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPCAReference) DeepCopyInto(out *MCPCAReference) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(MCPCAKeyReference)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(MCPCAKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPCAReference.
func (in *MCPCAReference) DeepCopy() *MCPCAReference {
	if in == nil {
		return nil
	}
	out := new(MCPCAReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPCNIDiagnosticsConfig) DeepCopyInto(out *MCPCNIDiagnosticsConfig) {
	*out = *in
	if in.KernelDebugImage != nil {
		in, out := &in.KernelDebugImage, &out.KernelDebugImage
		*out = new(string)
		**out = **in
	}
	if in.TCPDumpImage != nil {
		in, out := &in.TCPDumpImage, &out.TCPDumpImage
		*out = new(string)
		**out = **in
	}
	if in.PWRUImage != nil {
		in, out := &in.PWRUImage, &out.PWRUImage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPCNIDiagnosticsConfig.
func (in *MCPCNIDiagnosticsConfig) DeepCopy() *MCPCNIDiagnosticsConfig {
	if in == nil {
		return nil
	}
	out := new(MCPCNIDiagnosticsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MCPEmptyConfig) DeepCopyInto(out *MCPEmptyConfig) {
	{
		in := &in
		*out = in.DeepCopy()
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPHeader) DeepCopyInto(out *MCPHeader) {
	*out = *in
	in.ValueFrom.DeepCopyInto(&out.ValueFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPHeader.
func (in *MCPHeader) DeepCopy() *MCPHeader {
	if in == nil {
		return nil
	}
	out := new(MCPHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPHeaderValueSource) DeepCopyInto(out *MCPHeaderValueSource) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPHeaderValueSource.
func (in *MCPHeaderValueSource) DeepCopy() *MCPHeaderValueSource {
	if in == nil {
		return nil
	}
	out := new(MCPHeaderValueSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPHelmConfig) DeepCopyInto(out *MCPHelmConfig) {
	*out = *in
	if in.AllowedRegistries != nil {
		in, out := &in.AllowedRegistries, &out.AllowedRegistries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPHelmConfig.
func (in *MCPHelmConfig) DeepCopy() *MCPHelmConfig {
	if in == nil {
		return nil
	}
	out := new(MCPHelmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPKubeServerConfiguration) DeepCopyInto(out *MCPKubeServerConfiguration) {
	*out = *in
	if in.Toolsets != nil {
		in, out := &in.Toolsets, &out.Toolsets
		*out = new([]MCPToolsetSelection)
		if **in != nil {
			in, out := *in, *out
			*out = make([]MCPToolsetSelection, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.CABundleRefs != nil {
		in, out := &in.CABundleRefs, &out.CABundleRefs
		*out = make([]MCPCAReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPKubeServerConfiguration.
func (in *MCPKubeServerConfiguration) DeepCopy() *MCPKubeServerConfiguration {
	if in == nil {
		return nil
	}
	out := new(MCPKubeServerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPLogsConfig) DeepCopyInto(out *MCPLogsConfig) {
	*out = *in
	if in.LokiURL != nil {
		in, out := &in.LokiURL, &out.LokiURL
		*out = new(string)
		**out = **in
	}
	if in.UseRoute != nil {
		in, out := &in.UseRoute, &out.UseRoute
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPLogsConfig.
func (in *MCPLogsConfig) DeepCopy() *MCPLogsConfig {
	if in == nil {
		return nil
	}
	out := new(MCPLogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPMetricsConfig) DeepCopyInto(out *MCPMetricsConfig) {
	*out = *in
	if in.PrometheusURL != nil {
		in, out := &in.PrometheusURL, &out.PrometheusURL
		*out = new(string)
		**out = **in
	}
	if in.AlertmanagerURL != nil {
		in, out := &in.AlertmanagerURL, &out.AlertmanagerURL
		*out = new(string)
		**out = **in
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(string)
		**out = **in
	}
	if in.MaxMetricCardinality != nil {
		in, out := &in.MaxMetricCardinality, &out.MaxMetricCardinality
		*out = new(int64)
		**out = **in
	}
	if in.MaxLabelCardinality != nil {
		in, out := &in.MaxLabelCardinality, &out.MaxLabelCardinality
		*out = new(int64)
		**out = **in
	}
	if in.RangeQueryFullResponse != nil {
		in, out := &in.RangeQueryFullResponse, &out.RangeQueryFullResponse
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPMetricsConfig.
func (in *MCPMetricsConfig) DeepCopy() *MCPMetricsConfig {
	if in == nil {
		return nil
	}
	out := new(MCPMetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPNetObservConfig) DeepCopyInto(out *MCPNetObservConfig) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.CABundleRef != nil {
		in, out := &in.CABundleRef, &out.CABundleRef
		*out = new(MCPCAReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPNetObservConfig.
func (in *MCPNetObservConfig) DeepCopy() *MCPNetObservConfig {
	if in == nil {
		return nil
	}
	out := new(MCPNetObservConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPOSSMConfig) DeepCopyInto(out *MCPOSSMConfig) {
	*out = *in
	if in.CABundleRef != nil {
		in, out := &in.CABundleRef, &out.CABundleRef
		*out = new(MCPCAReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPOSSMConfig.
func (in *MCPOSSMConfig) DeepCopy() *MCPOSSMConfig {
	if in == nil {
		return nil
	}
	out := new(MCPOSSMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerConfig) DeepCopyInto(out *MCPServerConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]MCPHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerConfig.
func (in *MCPServerConfig) DeepCopy() *MCPServerConfig {
	if in == nil {
		return nil
	}
	out := new(MCPServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPToolsetSelection) DeepCopyInto(out *MCPToolsetSelection) {
	*out = *in
	if in.Core != nil {
		in, out := &in.Core, &out.Core
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(MCPHelmConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KCP != nil {
		in, out := &in.KCP, &out.KCP
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.OSSM != nil {
		in, out := &in.OSSM, &out.OSSM
		*out = new(MCPOSSMConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeVirt != nil {
		in, out := &in.KubeVirt, &out.KubeVirt
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.NetObserv != nil {
		in, out := &in.NetObserv, &out.NetObserv
		*out = new(MCPNetObservConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Tekton != nil {
		in, out := &in.Tekton, &out.Tekton
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ClusterDiagnostics != nil {
		in, out := &in.ClusterDiagnostics, &out.ClusterDiagnostics
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.CNIDiagnostics != nil {
		in, out := &in.CNIDiagnostics, &out.CNIDiagnostics
		*out = new(MCPCNIDiagnosticsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NetEdge != nil {
		in, out := &in.NetEdge, &out.NetEdge
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.OADP != nil {
		in, out := &in.OADP, &out.OADP
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.OVNKubernetes != nil {
		in, out := &in.OVNKubernetes, &out.OVNKubernetes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MCPMetricsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(MCPLogsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Traces != nil {
		in, out := &in.Traces, &out.Traces
		*out = new(MCPTracesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OtelCol != nil {
		in, out := &in.OtelCol, &out.OtelCol
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPToolsetSelection.
func (in *MCPToolsetSelection) DeepCopy() *MCPToolsetSelection {
	if in == nil {
		return nil
	}
	out := new(MCPToolsetSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPTracesConfig) DeepCopyInto(out *MCPTracesConfig) {
	*out = *in
	if in.TempoURL != nil {
		in, out := &in.TempoURL, &out.TempoURL
		*out = new(string)
		**out = **in
	}
	if in.UseRoute != nil {
		in, out := &in.UseRoute, &out.UseRoute
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPTracesConfig.
func (in *MCPTracesConfig) DeepCopy() *MCPTracesConfig {
	if in == nil {
		return nil
	}
	out := new(MCPTracesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelParametersSpec) DeepCopyInto(out *ModelParametersSpec) {
	*out = *in
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.ReasoningConfig != nil {
		in, out := &in.ReasoningConfig, &out.ReasoningConfig
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelParametersSpec.
func (in *ModelParametersSpec) DeepCopy() *ModelParametersSpec {
	if in == nil {
		return nil
	}
	out := new(ModelParametersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLSConfig) DeepCopyInto(out *OLSConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLSConfig.
func (in *OLSConfig) DeepCopy() *OLSConfig {
	if in == nil {
		return nil
	}
	out := new(OLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OLSConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLSConfigList) DeepCopyInto(out *OLSConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OLSConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLSConfigList.
func (in *OLSConfigList) DeepCopy() *OLSConfigList {
	if in == nil {
		return nil
	}
	out := new(OLSConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OLSConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLSConfigSpec) DeepCopyInto(out *OLSConfigSpec) {
	*out = *in
	in.LLMConfig.DeepCopyInto(&out.LLMConfig)
	in.OLSConfig.DeepCopyInto(&out.OLSConfig)
	out.OLSDataCollectorConfig = in.OLSDataCollectorConfig
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]MCPServerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make([]FeatureGate, len(*in))
		copy(*out, *in)
	}
	in.Audit.DeepCopyInto(&out.Audit)
	if in.AgenticOLS != nil {
		in, out := &in.AgenticOLS, &out.AgenticOLS
		*out = new(AgenticOLSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLSConfigSpec.
func (in *OLSConfigSpec) DeepCopy() *OLSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OLSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLSConfigStatus) DeepCopyInto(out *OLSConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiagnosticInfo != nil {
		in, out := &in.DiagnosticInfo, &out.DiagnosticInfo
		*out = make([]PodDiagnostic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLSConfigStatus.
func (in *OLSConfigStatus) DeepCopy() *OLSConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OLSConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLSDataCollectorSpec) DeepCopyInto(out *OLSDataCollectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLSDataCollectorSpec.
func (in *OLSDataCollectorSpec) DeepCopy() *OLSDataCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(OLSDataCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLSSpec) DeepCopyInto(out *OLSSpec) {
	*out = *in
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(GuardrailsConfig)
		(*in).DeepCopyInto(*out)
	}
	out.ConversationCache = in.ConversationCache
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	if in.QueryFilters != nil {
		in, out := &in.QueryFilters, &out.QueryFilters
		*out = make([]QueryFiltersSpec, len(*in))
		copy(*out, *in)
	}
	out.UserDataCollection = in.UserDataCollection
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(TLSConfig)
		**out = **in
	}
	if in.AdditionalCAConfigMapRef != nil {
		in, out := &in.AdditionalCAConfigMapRef, &out.AdditionalCAConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.TLSSecurityProfile != nil {
		in, out := &in.TLSSecurityProfile, &out.TLSSecurityProfile
		*out = new(configv1.TLSSecurityProfile)
		(*in).DeepCopyInto(*out)
	}
	if in.IntrospectionEnabled != nil {
		in, out := &in.IntrospectionEnabled, &out.IntrospectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AuditEventsEnabled != nil {
		in, out := &in.AuditEventsEnabled, &out.AuditEventsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MCPKubeServerConfig != nil {
		in, out := &in.MCPKubeServerConfig, &out.MCPKubeServerConfig
		*out = new(MCPKubeServerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ProxyConfig != nil {
		in, out := &in.ProxyConfig, &out.ProxyConfig
		*out = new(ProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RAG != nil {
		in, out := &in.RAG, &out.RAG
		*out = make([]RAGSpec, len(*in))
		copy(*out, *in)
	}
	if in.QuotaHandlersConfig != nil {
		in, out := &in.QuotaHandlersConfig, &out.QuotaHandlersConfig
		*out = new(QuotaHandlersConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(Storage)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ToolFilteringConfig != nil {
		in, out := &in.ToolFilteringConfig, &out.ToolFilteringConfig
		*out = new(ToolFilteringConfig)
		**out = **in
	}
	if in.ToolsApprovalConfig != nil {
		in, out := &in.ToolsApprovalConfig, &out.ToolsApprovalConfig
		*out = new(ToolsApprovalConfig)
		**out = **in
	}
	if in.CredentialHotReload != nil {
		in, out := &in.CredentialHotReload, &out.CredentialHotReload
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLSSpec.
func (in *OLSSpec) DeepCopy() *OLSSpec {
	if in == nil {
		return nil
	}
	out := new(OLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDiagnostic) DeepCopyInto(out *PodDiagnostic) {
	*out = *in
	if in.ExitCode != nil {
		in, out := &in.ExitCode, &out.ExitCode
		*out = new(int32)
		**out = **in
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDiagnostic.
func (in *PodDiagnostic) DeepCopy() *PodDiagnostic {
	if in == nil {
		return nil
	}
	out := new(PodDiagnostic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresSpec) DeepCopyInto(out *PostgresSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresSpec.
func (in *PostgresSpec) DeepCopy() *PostgresSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]ModelSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GoogleVertexConfig != nil {
		in, out := &in.GoogleVertexConfig, &out.GoogleVertexConfig
		*out = new(VertexConfig)
		**out = **in
	}
	if in.GoogleVertexAnthropicConfig != nil {
		in, out := &in.GoogleVertexAnthropicConfig, &out.GoogleVertexAnthropicConfig
		*out = new(VertexConfig)
		**out = **in
	}
	if in.TLSSecurityProfile != nil {
		in, out := &in.TLSSecurityProfile, &out.TLSSecurityProfile
		*out = new(configv1.TLSSecurityProfile)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyCACertConfigMapRef) DeepCopyInto(out *ProxyCACertConfigMapRef) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyCACertConfigMapRef.
func (in *ProxyCACertConfigMapRef) DeepCopy() *ProxyCACertConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ProxyCACertConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	if in.ProxyCACertificateRef != nil {
		in, out := &in.ProxyCACertificateRef, &out.ProxyCACertificateRef
		*out = new(ProxyCACertConfigMapRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryFiltersSpec) DeepCopyInto(out *QueryFiltersSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryFiltersSpec.
func (in *QueryFiltersSpec) DeepCopy() *QueryFiltersSpec {
	if in == nil {
		return nil
	}
	out := new(QueryFiltersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaHandlersConfig) DeepCopyInto(out *QuotaHandlersConfig) {
	*out = *in
	if in.LimitersConfig != nil {
		in, out := &in.LimitersConfig, &out.LimitersConfig
		*out = make([]LimiterConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaHandlersConfig.
func (in *QuotaHandlersConfig) DeepCopy() *QuotaHandlersConfig {
	if in == nil {
		return nil
	}
	out := new(QuotaHandlersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RAGSpec) DeepCopyInto(out *RAGSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RAGSpec.
func (in *RAGSpec) DeepCopy() *RAGSpec {
	if in == nil {
		return nil
	}
	out := new(RAGSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	out.KeyCertSecretRef = in.KeyCertSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolFilteringConfig) DeepCopyInto(out *ToolFilteringConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolFilteringConfig.
func (in *ToolFilteringConfig) DeepCopy() *ToolFilteringConfig {
	if in == nil {
		return nil
	}
	out := new(ToolFilteringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolResultInspectionConfig) DeepCopyInto(out *ToolResultInspectionConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolResultInspectionConfig.
func (in *ToolResultInspectionConfig) DeepCopy() *ToolResultInspectionConfig {
	if in == nil {
		return nil
	}
	out := new(ToolResultInspectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsApprovalConfig) DeepCopyInto(out *ToolsApprovalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsApprovalConfig.
func (in *ToolsApprovalConfig) DeepCopy() *ToolsApprovalConfig {
	if in == nil {
		return nil
	}
	out := new(ToolsApprovalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDataCollectionSpec) DeepCopyInto(out *UserDataCollectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDataCollectionSpec.
func (in *UserDataCollectionSpec) DeepCopy() *UserDataCollectionSpec {
	if in == nil {
		return nil
	}
	out := new(UserDataCollectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VertexConfig) DeepCopyInto(out *VertexConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VertexConfig.
func (in *VertexConfig) DeepCopy() *VertexConfig {
	if in == nil {
		return nil
	}
	out := new(VertexConfig)
	in.DeepCopyInto(out)
	return out
}
